/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as privateCreateOrganizationRouteImport } from './routes/(private)/create-organization'
import { Route as publicSignInRouteImport } from './routes/(public)/sign-in'
import { Route as publicSignUpRouteImport } from './routes/(public)/sign-up'
import { Route as privateOrgOrgSlugRouteRouteImport } from './routes/(private)/org/$orgSlug/route'
import { Route as privateOrgOrgSlugBotsRouteImport } from './routes/(private)/org/$orgSlug/bots'
import { Route as privateOrgOrgSlugDashboardRouteImport } from './routes/(private)/org/$orgSlug/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateCreateOrganizationRoute =
  privateCreateOrganizationRouteImport.update({
    id: '/create-organization',
    path: '/create-organization',
    getParentRoute: () => privateRouteRoute,
  } as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicRouteRoute,
} as any)
const privateOrgOrgSlugRouteRoute = privateOrgOrgSlugRouteRouteImport.update({
  id: '/org/$orgSlug',
  path: '/org/$orgSlug',
  getParentRoute: () => privateRouteRoute,
} as any)
const privateOrgOrgSlugBotsRoute = privateOrgOrgSlugBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => privateOrgOrgSlugRouteRoute,
} as any)
const privateOrgOrgSlugDashboardRoute =
  privateOrgOrgSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => privateOrgOrgSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-organization': typeof privateCreateOrganizationRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/org/$orgSlug': typeof privateOrgOrgSlugRouteRouteWithChildren
  '/org/$orgSlug/bots': typeof privateOrgOrgSlugBotsRoute
  '/org/$orgSlug/dashboard': typeof privateOrgOrgSlugDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-organization': typeof privateCreateOrganizationRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/org/$orgSlug': typeof privateOrgOrgSlugRouteRouteWithChildren
  '/org/$orgSlug/bots': typeof privateOrgOrgSlugBotsRoute
  '/org/$orgSlug/dashboard': typeof privateOrgOrgSlugDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(private)': typeof privateRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(private)/create-organization': typeof privateCreateOrganizationRoute
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/(private)/org/$orgSlug': typeof privateOrgOrgSlugRouteRouteWithChildren
  '/(private)/org/$orgSlug/bots': typeof privateOrgOrgSlugBotsRoute
  '/(private)/org/$orgSlug/dashboard': typeof privateOrgOrgSlugDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organization'
    | '/sign-in'
    | '/sign-up'
    | '/org/$orgSlug'
    | '/org/$orgSlug/bots'
    | '/org/$orgSlug/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organization'
    | '/sign-in'
    | '/sign-up'
    | '/org/$orgSlug'
    | '/org/$orgSlug/bots'
    | '/org/$orgSlug/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(private)'
    | '/(public)'
    | '/(private)/create-organization'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
    | '/(private)/org/$orgSlug'
    | '/(private)/org/$orgSlug/bots'
    | '/(private)/org/$orgSlug/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/create-organization': {
      id: '/(private)/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof privateCreateOrganizationRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(private)/org/$orgSlug': {
      id: '/(private)/org/$orgSlug'
      path: '/org/$orgSlug'
      fullPath: '/org/$orgSlug'
      preLoaderRoute: typeof privateOrgOrgSlugRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(private)/org/$orgSlug/bots': {
      id: '/(private)/org/$orgSlug/bots'
      path: '/bots'
      fullPath: '/org/$orgSlug/bots'
      preLoaderRoute: typeof privateOrgOrgSlugBotsRouteImport
      parentRoute: typeof privateOrgOrgSlugRouteRoute
    }
    '/(private)/org/$orgSlug/dashboard': {
      id: '/(private)/org/$orgSlug/dashboard'
      path: '/dashboard'
      fullPath: '/org/$orgSlug/dashboard'
      preLoaderRoute: typeof privateOrgOrgSlugDashboardRouteImport
      parentRoute: typeof privateOrgOrgSlugRouteRoute
    }
  }
}

interface privateOrgOrgSlugRouteRouteChildren {
  privateOrgOrgSlugBotsRoute: typeof privateOrgOrgSlugBotsRoute
  privateOrgOrgSlugDashboardRoute: typeof privateOrgOrgSlugDashboardRoute
}

const privateOrgOrgSlugRouteRouteChildren: privateOrgOrgSlugRouteRouteChildren =
  {
    privateOrgOrgSlugBotsRoute: privateOrgOrgSlugBotsRoute,
    privateOrgOrgSlugDashboardRoute: privateOrgOrgSlugDashboardRoute,
  }

const privateOrgOrgSlugRouteRouteWithChildren =
  privateOrgOrgSlugRouteRoute._addFileChildren(
    privateOrgOrgSlugRouteRouteChildren,
  )

interface privateRouteRouteChildren {
  privateCreateOrganizationRoute: typeof privateCreateOrganizationRoute
  privateOrgOrgSlugRouteRoute: typeof privateOrgOrgSlugRouteRouteWithChildren
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateCreateOrganizationRoute: privateCreateOrganizationRoute,
  privateOrgOrgSlugRouteRoute: privateOrgOrgSlugRouteRouteWithChildren,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicSignInRoute: typeof publicSignInRoute
  publicSignUpRoute: typeof publicSignUpRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicSignInRoute: publicSignInRoute,
  publicSignUpRoute: publicSignUpRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  privateRouteRoute: privateRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
