/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as privateRouteRouteImport } from './routes/(private)/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as privateMainRouteRouteImport } from './routes/(private)/_main/route'
import { Route as publicSignInRouteImport } from './routes/(public)/sign-in'
import { Route as publicSignUpRouteImport } from './routes/(public)/sign-up'
import { Route as privateMainBotsRouteImport } from './routes/(private)/_main/bots'
import { Route as privateMainDashboardRouteImport } from './routes/(private)/_main/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const privateRouteRoute = privateRouteRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateMainRouteRoute = privateMainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => privateRouteRoute,
} as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicRouteRoute,
} as any)
const privateMainBotsRoute = privateMainBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => privateMainRouteRoute,
} as any)
const privateMainDashboardRoute = privateMainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => privateMainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/bots': typeof privateMainBotsRoute
  '/dashboard': typeof privateMainDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/bots': typeof privateMainBotsRoute
  '/dashboard': typeof privateMainDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(private)': typeof privateRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(private)/_main': typeof privateMainRouteRouteWithChildren
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/(private)/_main/bots': typeof privateMainBotsRoute
  '/(private)/_main/dashboard': typeof privateMainDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/sign-up' | '/bots' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/sign-up' | '/bots' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(private)'
    | '/(public)'
    | '/(private)/_main'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
    | '/(private)/_main/bots'
    | '/(private)/_main/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  privateRouteRoute: typeof privateRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/_main': {
      id: '/(private)/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateMainRouteRouteImport
      parentRoute: typeof privateRouteRoute
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(private)/_main/bots': {
      id: '/(private)/_main/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof privateMainBotsRouteImport
      parentRoute: typeof privateMainRouteRoute
    }
    '/(private)/_main/dashboard': {
      id: '/(private)/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof privateMainDashboardRouteImport
      parentRoute: typeof privateMainRouteRoute
    }
  }
}

interface privateMainRouteRouteChildren {
  privateMainBotsRoute: typeof privateMainBotsRoute
  privateMainDashboardRoute: typeof privateMainDashboardRoute
}

const privateMainRouteRouteChildren: privateMainRouteRouteChildren = {
  privateMainBotsRoute: privateMainBotsRoute,
  privateMainDashboardRoute: privateMainDashboardRoute,
}

const privateMainRouteRouteWithChildren =
  privateMainRouteRoute._addFileChildren(privateMainRouteRouteChildren)

interface privateRouteRouteChildren {
  privateMainRouteRoute: typeof privateMainRouteRouteWithChildren
}

const privateRouteRouteChildren: privateRouteRouteChildren = {
  privateMainRouteRoute: privateMainRouteRouteWithChildren,
}

const privateRouteRouteWithChildren = privateRouteRoute._addFileChildren(
  privateRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicSignInRoute: typeof publicSignInRoute
  publicSignUpRoute: typeof publicSignUpRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicSignInRoute: publicSignInRoute,
  publicSignUpRoute: publicSignUpRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  privateRouteRoute: privateRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
